import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState ,useEffect} from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [response, setResponse] = useState(null)
  const [gstnum, setGstnum] = useState([])
  const [details, setDetails] = useState([])

  //write the logic for checking GSTIN
    const checkGST = async gstnum => {
    setResponse(false);
    const res = await fetch(`/api/handler/${gstnum}`)
    const data = await res.json();
    if(data.error){
      setResponse(false);
      alert('Error: ' + data.message);
    }
    else{
      setDetails(data.data);
      setResponse(true);
    }
  }

  function display(data){
    
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>WELCOME TO THE GST AND PAN VALIDATOR FOR BILLS! 
          <br />
          JUST ENTER THE GST OR PAN NUMBER ON YOUR BILLS AND VALIDATE IF THE ORGANIZATION IS LEGITIMATE!
        </p>
        <div className='GSTinput'>
          <label htmlFor='GST'>GST/PAN Number: </label>
          <input type='text' placeholder='ex: 27CBKPA9141P1ZC' value={gstnum} onChange={(e) => setGstnum(e.target.value)}></input>
          <button onClick={() => checkGST(gstnum)}>Check Validity</button>
        </div>
        {
        response ?
        (
          <div className='response'>
            <p>Details found!</p>
            <table>
              <tbody>
              {
                display(details)
              }
            </tbody>
            </table>
          </div>
        )
        :
        (
          <div className='response'>
            {/* <h3>Details not found!</h3>
            <pre id="jsondata">
              Please check the GST/PAN number and try again!
            </pre> */}
          </div>
        )
        }
      </main>
    </>
  )
}
