import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [gstnum, setGstnum] = useState('')
  const [pannum, setPannum] = useState('')

  //write the logic for checking the number
    const checkGST = async gstnum => {
    const res = await fetch(`/api/handler/${gstnum}`)
    const data = await res.json();
    console.log(data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>WELCOME TO THE GST AND PAN VALIDATOR FOR BILLS! 
          <br />
          JUST ENTER THE GST OR PAN NUMBER ON YOUR BILLS AND VALIDATE IF THE ORGANIZATION IS LEGITIMATE!
        </p>
        <div className='GSTinput'>
          <label htmlFor='GST'>GST Number: </label>
          <input type='text' placeholder='Enter the 15 digit GST number here' value={gstnum} onChange={(e) => setGstnum(e.target.value)}></input>
          <button onClick={() => checkGST(gstnum)}>Check Validity</button>
        </div>
        <p>OR</p>
        <div className='PANinput'>
          <label htmlFor='PAN'>PAN Number: </label>
          <input placeholder='Enter the PAN number here: '></input>
          <button>Check Validity</button>
        </div>
      </main>
    </>
  )
}
